import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export async function getServerSideProps() {
  const props = {
    experiments: {
      greeting: 'About info',
    },
  }
  console.log('About server-side props: %o', props)
  return {
    props,
  }
}

export default function About({ experiments }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>About</h1>

        <p className={styles.description} data-cy="greeting">
          {experiments.greeting || 'Silence'}
        </p>

        <Link href="/">
          <a>Home</a>
        </Link>
      </main>
    </div>
  )
}
