import Head from 'next/head'
import styles from '../styles/Home.module.css'

export async function getServerSideProps() {
  const props = {
    experiments: {
      greeting: 'Server-side says hello!',
    },
  }
  console.log('server-side props: %o', props)
  return {
    props,
  }
}

export default function Home({ experiments }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hello there</h1>

        <p className={styles.description}>
          {experiments.greeting || 'Silence'}
        </p>
      </main>
    </div>
  )
}
